clean: true
author: Joshua Emmons
author_url: https://figure.ink
github_url: https://github.com/jemmons/Medea
module: Medea
module_version: 1.1
xcodebuild_arguments: 
  - '-project'
  - 'Support/Medea.xcodeproj'
  
custom_categories:
  - name: Public Interface
    children:
    - JSONHelper
